### ISSUE TITLE
Shadowlands Pre-Patch errors

### ISSUE THREAD

**Issue by Meebsy** [Jaliborc/PetTracker#213]
`Message: ...ce\AddOns\PetTracker\addons\main\features\gossip.lua:44: hooksecurefunc(): SelectGossipOption is not a function
Time: Wed Oct 14 09:49:32 2020
Count: 1
Stack: ...ce\AddOns\PetTracker\addons\main\features\gossip.lua:44: hooksecurefunc(): SelectGossipOption is not a function`

Version 8.3.8

**Comment by Meebsy** [comment]
`Message: ...ddOns\PetTracker\addons\main\features\objectives.lua:78: attempt to index field 'BlocksFrame' (a nil value)
Time: Wed Oct 14 09:49:34 2020
Count: 1
Stack: ...ddOns\PetTracker\addons\main\features\objectives.lua:78: attempt to index field 'BlocksFrame' (a nil value)`

**Comment by Meebsy** [comment]
`Message: ...ddOns\PetTracker\addons\main\features\objectives.lua:78: attempt to index field 'BlocksFrame' (a nil value)
Time: Wed Oct 14 09:49:37 2020
Count: 3
Stack: ...ddOns\PetTracker\addons\main\features\objectives.lua:78: attempt to index field 'BlocksFrame' (a nil value)`

**Comment by fuba82** [comment]
this should fix it, **BUT** it need to be tested!  
  
replace **"...\Interface\AddOns\PetTracker\addons\main\features\gossip.lua"**
```
hooksecurefunc('SelectGossipOption', function(index)
```
with
```
hooksecurefunc(C_GossipInfo, 'SelectOption', function(index)
```
this **should** fix the first error!  
  
also replace **"...\Interface\AddOns\PetTracker\addons\main\features\objectives.lua"**
```
local height = DEFAULT_OBJECTIVE_TRACKER_MODULE.BlocksFrame.contentsHeight or 0
```
with
```
local height = ObjectiveTrackerFrame.BlocksFrame.contentsHeight or 0
```
this **should** fix the second error  
  
And also change in **all** PetTracker TOC files:
```
## Interface: 80300
```
to this:
```
## Interface: 90001
```

**Comment by ObiWahn86** [comment]
Here's another one from 9.0.1:

```
Message: ...Ons\PetTracker\addons\main\classes\maps\rivalPin.lua:37: attempt to call global 'IsQuestFlaggedCompleted' (a nil value)
Time: Wed Oct 14 17:43:40 2020
Count: 10
Stack: ...Ons\PetTracker\addons\main\classes\maps\rivalPin.lua:37: attempt to call global 'IsQuestFlaggedCompleted' (a nil value)
```

**Comment by ObiWahn86** [comment]
And this one:
```
Message: ...terface\AddOns\PetTracker\addons\battle\listener.lua:101: attempt to call field 'GetDate' (a nil value)
Time: Wed Oct 14 18:07:11 2020
Count: 1
Stack: ...terface\AddOns\PetTracker\addons\battle\listener.lua:101: attempt to call field 'GetDate' (a nil value)
```

**Comment by sauljaffe** [comment]
Don't know if it helps but I'm seeing the same error and have more, hopefully useful information:

165x ...ddOns\PetTracker\addons\main\features\objectives.lua:78: attempt to index field 'BlocksFrame' (a nil value)
[string "@PetTracker\addons\main\features\objectives.lua"]:78: in function `GetUsedHeight'
[string "@PetTracker\addons\main\features\objectives.lua"]:48: in function <...ddOns\PetTracker\addons\main\features\objectives.lua:47>
[string "=[C]"]: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:937: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:936>
[string "=[C]"]: in function `GetHeight'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:1339: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:1325>
[string "=[C]"]: in function `ObjectiveTracker_Update'
[string "@Blizzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua"]:917: in function <...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:835>

Locals:
self = <unnamed> {
 0 = <userdata>
 Lines = <table> {
 }
 Index = 1
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Update = <function> defined @PetTracker\addons\main\features\objectives.lua:69
 Anchor = <unnamed> {
 }
 SendMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 UnregisterSignal = <function> defined @PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:78
 RegisterEvent = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 MaxEntries = 0
 SendSignal = <function> defined @PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:82
 GetUsedHeight = <function> defined @PetTracker\addons\main\features\objectives.lua:77
 OnEnable = <function> defined @PetTracker\addons\main\features\objectives.lua:35
 Header = <unnamed> {
 }
 RegisterSignal = <function> defined @PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:74
 NewModule = <function> defined @PetTracker\libs\WildAddon-1.0\WildAddon-1.0.lua:68
 UnregisterAllEvents = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UnregisterEvent = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 Tag = "PETTRACKER_"
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'BlocksFrame' (a nil value)"

**Comment by fubaWoW** [comment]
Another Error that breaks (AGAIN and again) another addon (Handynotes: Vision's of N'Zoth)...
only because of the "Sushi" s h i t  dropdown menu... -.-

```
1x ...PetTracker\libs\Sushi-3.1-4\classes\drops\Dropdown.lua:136: Invalid data provided for `:SetBackdrop`
[string "=[C]"]: in function `assert'
[string "@PetTracker\libs\Sushi-3.1-4\classes\drops\Dropdown.lua"]:136: in function `SetBackdrop'
[string "@PetTracker\libs\Sushi-3.1-4\classes\drops\Dropdown.lua"]:48: in function `New'
[string "@PetTracker\libs\Sushi-3.1-4\classes\drops\Dropdown.lua"]:57: in function `Toggle'
[string "@PetTracker\addons\main\features\mapSearch.lua"]:124: in function `ToggleTrackingTypes'
[string "@PetTracker\addons\main\features\mapSearch.lua"]:71: in function <PetTracker\addons\main\features\mapSearch.lua:71>

Locals:
(*temporary) = false
(*temporary) = "Invalid data provided for `:SetBackdrop`"

```

**Comment by spiralofhope** [comment]
@fubaWoW

That's an issue with Sushi-3.1, a library which is used in PetTracker:

https://github.com/Jaliborc/Sushi-3.1/issues/10

I've been fixing other bugs lately, I can probably tackle PetTracker and that one if I can get you all as testers.

**Comment by Ludovicus-Maior** [comment]
Count me in a a tester.

**Comment by spiralofhope** [comment]
### update

Thanks to @fuba82 for [those changes](https://github.com/Jaliborc/PetTracker/issues/213#issuecomment-708431256).  They have been brought into [a pull request](https://github.com/Jaliborc/PetTracker/pull/214) which will make the author's life easier.

Lastly, I did find [one other problem with rivals](https://github.com/Jaliborc/PetTracker/issues/215).  I am momentarily stumped by this; it will require some investigation.

### How can you make PetTracker work for you?

Until the author returns:

1. make these changes yourself:
https://github.com/Jaliborc/PetTracker/pull/214/commits/eb82e4fcdf4961c7d31d967830ac7cef7e3a5f70
https://github.com/Jaliborc/PetTracker/pull/214/commits/8feca83fc179908671320f0997d12663ea4a9f6f

2. Delete `Libs/Sushi-3.1` and re-download it [from GitHub](https://github.com/Jaliborc/Sushi-3.1):  https://github.com/Jaliborc/Sushi-3.1/archive/master.zip

I *think* this is all, but I haven't done anything pet-related in two expansions so I can't even remember all of what this addon does.  ><

If you find future problems, please open a new ticket https://github.com/Jaliborc/PetTracker/issues/new/choose

You can `@spiralofhope` in there if you think I can help (like if you found a solution!), but I'm not a programmer (no, really)

**Comment by spiralofhope** [comment]
Okay gang, things seem to be working well. I'm happy to have helped, but I'm burnt out. :)

It's all packaged into [one big pull request](https://github.com/Jaliborc/PetTracker/pull/214/) for the author.

[My update instructions are above](https://github.com/Jaliborc/PetTracker/issues/213#issuecomment-708576526).

**Comment by fubaWoW** [comment]
1st, Another LUA error!

**How to Reproduce:**
Show "Species" on the WorldMap and just click on any Species Icon on the WorldMap
This will open the Pet Journal and triggers the LUA Error here:
```
1x ...s\PetTracker\addons\main\classes\abstract\specie.lua:26: attempt to index a nil value
[string "@PetTracker\addons\main\classes\abstract\specie.lua"]:26: in function `GetID'
[string "@PetTracker\addons\main\classes\abstract\pet-Pet.lua"]:33: in function `Display'
[string "@PetTracker\addons\main\classes\maps\speciePin.lua"]:67: in function <...ns\PetTracker\addons\main\classes\maps\speciePin.lua:65>

Locals:
self = <table> {
 specie = 267
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"
```


---

2nd, The Search bar:
The "Search Bar" stay in actual state (Visible or Invisible) when toggle "Species" on the WorldMap.  
But it is visible if "Species" is enabled or invisible of disabled **and** you Reload the UI!  

---

3rd, Another thing is, the "Search Bar" overlaps the new Map-Pin Button:  
![image](https://user-images.githubusercontent.com/41425685/96132418-af43c880-0efa-11eb-9743-f7cd4a3b0020.png)

**Comment by rhainstorm** [comment]
> local height = ObjectiveTrackerFrame.BlocksFrame.contentsHeight or 0

im not seeing the second fix in the lua  this one 
also replace "...\Interface\AddOns\PetTracker\addons\main\features\objectives.lua"

local height = DEFAULT_OBJECTIVE_TRACKER_MODULE.BlocksFrame.contentsHeight or 0
with

local height = ObjectiveTrackerFrame.BlocksFrame.contentsHeight or 0
this should fix the second error

here is my objectives.lua
--[[
Copyright 2012-2020 João Cardoso
PetTracker is distributed under the terms of the GNU General Public License (Version 3).
As a special exception, the copyright holders of this addon do not give permission to
redistribute and/or modify it.

This addon is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with the addon. If not, see <http://www.gnu.org/licenses/gpl-3.0.txt>.

This file is part of PetTracker.
--]]

if IsAddOnLoaded('Carbonite.Quests') then
	return
end

local ADDON, Addon = ...
local Parent, HeaderButton = ObjectiveTrackerBlocksFrame, ObjectiveTrackerFrame.HeaderMenu
local Objectives = Addon:NewModule('Objectives', Addon.Tracker(Parent))

do
	OBJECTIVE_TRACKER_ADDONS = OBJECTIVE_TRACKER_ADDONS or {}
	tinsert(OBJECTIVE_TRACKER_ADDONS, 0)
	Objectives.Index = #OBJECTIVE_TRACKER_ADDONS
end


--[[ Startup ]]--

function Objectives:OnEnable()
	local header = CreateFrame('Button', nil, self, 'ObjectiveTrackerHeaderTemplate')
	header:SetScript('OnClick', self.ToggleDropdown)
	header:RegisterForClicks('anyUp')
	header:SetPoint('TOPLEFT')
	header.Text:SetText(PETS)
	header:Show()

	self.Anchor:SetPoint('TOPLEFT', header, 'BOTTOMLEFT', -4, -10)
	self.Anchor:SetScript('OnMouseDown', self.ToggleOptions)
	self.Header = header

	hooksecurefunc('ObjectiveTracker_Update', function()
		local off = self:GetUsedHeight()
		local availableEntries = floor(((Parent.maxHeight or 0) - off - 45) / 20)

		if availableEntries ~= self.MaxEntries then
			self.MaxEntries = availableEntries
			self:Update()
		end

		self:SetPoint('TOPLEFT', Parent, -10, -off)
	end)

	HeaderButton:HookScript('OnHide', function()
		if self:IsShown() then
			HeaderButton:Show()
		end
	end)
end


--[[ API Override ]]--

function Objectives:Update()
	self:GetClass().Update(self)
	self:SetShown(Addon.sets.trackPets and self.Anchor:IsShown())

	HeaderButton:SetShown(Parent.currentBlock or self:IsShown())
	OBJECTIVE_TRACKER_ADDONS[self.Index] = self:IsShown() and self:GetHeight() or 0
end

function Objectives:GetUsedHeight()
	local height = Parent.contentsHeight or 0
	for i = 1, self.Index-1 do
		height = height + OBJECTIVE_TRACKER_ADDONS[i]
	end

	if height > 0 then
		height = height + 15
	end

	return height
end

I just updated it and have pre shadowlands. i was told in my ticket on my lua errors this was post was my fix
ty for any help

**Comment by fubaWoW** [comment]
it is also not fixed when click on a Pet-Pin on the Worldmap!
```
1x ...s\PetTracker\addons\main\classes\abstract\specie.lua:26: attempt to index a nil value
[string "@PetTracker\addons\main\classes\abstract\specie.lua"]:26: in function `GetID'
[string "@PetTracker\addons\main\classes\abstract\pet-Pet.lua"]:33: in function `Display'
[string "@PetTracker\addons\main\classes\maps\speciePin.lua"]:67: in function <...ns\PetTracker\addons\main\classes\maps\speciePin.lua:65>

Locals:
self = <table> {
 specie = 389
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index a nil value"

```
but -> "issue closed"...

**Comment by spiralofhope** [comment]
For anyone still having errors, please

- Make sure you update (even if you have to [download it manually](https://github.com/Jaliborc/PetTracker/archive/master.zip) and unzip it overtop of your current `PetTracker` folder.
- Then reproduce it. 
- Then if it persists, [open a new ticket](https://github.com/Jaliborc/PetTracker/issues/new/choose).

This will keep things clean for the developer.
